# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 896fdacfcd475a193df429558dfa784b8b4466a372cb6c7ce7633e4d073f5fedbdc4dc6b53c2429b6ff18b8bb685caad420c41940413c0c1b68261889c50112c

test:
  secret_key_base: 78187ad6308d8a736b2f70261fbeb8291906b4dbe88c09e08ea0065c7d2f38700a135488ace5cc2ac0a671c023ae71c2ff7f0b721cb5ff8ed15dee633a3718c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
